# Data Gathering

## Sources of Data
A vast amount of historical data can be found in files such as:
* MS Word documents
* Emails
* Spreadsheets
* MS PowerPoints
* PDFs
* HTML
* Plaintext files

**Public and Private Archives**
CSV, JSON, and XML files use plaintext, a common format, and are compatible with a wide range of applications. The Web can be mined for data using a web scraping application. The IoT uses sensors to create data. Sensors in smartphones, cars, airplanes, street lamps, and home appliances capture raw data.

**Open Data and Private Data**
1. **Open Data**: The Open Knowledge Foundation describes Open Data as "any content, information or data that people are free to use, reuse, and redistribute without any legal, technological, or social restriction."
2. **Private Data**: Data related to an expectation of privacy and regulated by a particular country/government.

**Structured and Unstructured Data**
1. **Structured Data**: Data entered and maintained in fixed fields within a file or record. Easily entered, classified, queried, and analyzed. Relational databases or spreadsheets.
2. **Unstructured Data**: Lacks organization. Raw data such as photo contents, audio, video, web pages, blogs, books, journals, white papers, PowerPoint presentations, articles, email, wikis, word processing documents, and text in general.

In [19]:
pip install opencv-python

Requirement already satisfied: opencv-python in c:\users\tipqc\appdata\local\programs\python\python312\lib\site-packages (4.13.0.92)
Requirement already satisfied: numpy>=2 in c:\users\tipqc\appdata\local\programs\python\python312\lib\site-packages (from opencv-python) (2.4.2)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [20]:
import cv2 #Without colab stuff

webcam = cv2.VideoCapture(0)

if not webcam.isOpened():
    print("Error: Could not open webcam.")
    exit()

print("Press 's' to save an image, or 'q' to quit.")

while True:
    try:
        check, frame = webcam.read()
        if not check:
            print("Failed to grab frame")
            break

        #Display the live feed
        cv2.imshow("Capturing", frame)
        
        key = cv2.waitKey(1)
        
        #Save image when 's' is pressed
        if key == ord('s'):
            cv2.imwrite(filename='saved_img.jpg', img=frame)
            print("Processing image...")
            
            #Read back and process
            img_new = cv2.imread('saved_img.jpg', cv2.IMREAD_GRAYSCALE)
            cv2.imshow("Captured Image", img_new)
            cv2.waitKey(1650)
            
            #Further processing
            gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
            img_resized = cv2.resize(gray, (28, 28))
            cv2.imwrite(filename='saved_img-final.jpg', img=img_resized)
            print("Image saved and resized to 28x28!")
            break

        #Quit when 'q' is pressed
        elif key == ord('q'):
            print("Turning off camera.")
            break

    except KeyboardInterrupt:
        break

#Cleanup
webcam.release()
cv2.destroyAllWindows()
print("Program ended.")

Error: Could not open webcam.
Press 's' to save an image, or 'q' to quit.
Failed to grab frame
Program ended.

In [21]:
!pip3 install sounddevice
!pip3 install wavio
!pip3 install scipy
!apt-get install libportaudio2 -y

'pip3' is not recognized as an internal or external command,
operable program or batch file.
'pip3' is not recognized as an internal or external command,
operable program or batch file.
'pip3' is not recognized as an internal or external command,
operable program or batch file.
'apt-get' is not recognized as an internal or external command,
operable program or batch file.

In [22]:
# Example of gathering voice data using microphone
# Note: Requires system level libraries (e.g. libportaudio2 on Ubuntu)

import sounddevice as sd
from scipy.io.wavfile import write
import wavio as wv

# Sampling frequency
freq = 44100
# Recording duration
duration = 5

# Start recorder with the given values of duration and sample frequency
recording = sd.rec(int(duration * freq), samplerate=freq, channels=2)

# Record audio for the given number of seconds
sd.wait()

# This will convert the NumPy array to an audio file with the given sampling frequency
write("recording0.wav", freq, recording)

# Convert the NumPy array to audio file
wv.write("recording1.wav", recording, freq, sampwidth=2)
print("Audio saved successfully!")

ModuleNotFoundError: No module named 'sounddevice'

:

# Web Scraping

Web scraping, web harvesting, or web data extraction is data scraping used for extracting data from websites. The web scraping software may directly access the World Wide Web using the Hypertext Transfer Protocol or a web browser. 

While web scraping can be done manually by a software user, the term typically refers to automated processes implemented using a bot or web crawler. It is a form of copying in which specific data is gathered and copied from the web, typically into a central local database or spreadsheet, for later retrieval or analysis.

## Image Scraping using BeautifulSoup and Request

In [1]:
!pip install bs4
!pip install requests

'pip' is not recognized as an internal or external command,
operable program or batch file.
'pip' is not recognized as an internal or external command,
operable program or batch file.

In [2]:
import requests
from bs4 import BeautifulSoup

def getdata(url):
    r = requests.get(url)
    return r.text

htmldata = getdata("https://www.google.com/")
soup = BeautifulSoup(htmldata, 'html.parser')

for item in soup.find_all('img'):
    print(item['src'])

/images/branding/googlelogo/1x/googlelogo_white_background_color_272x92dp.png

In [3]:
!pip install selenium
!apt-get update
!apt install chromium-chromedriver -y
!cp /usr/lib/chromium-browser/chromedriver /usr/bin

'pip' is not recognized as an internal or external command,
operable program or batch file.

'apt-get' is not recognized as an internal or external command,
operable program or batch file.
'apt' is not recognized as an internal or external command,
operable program or batch file.
'cp' is not recognized as an internal or external command,
operable program or batch file.

In [9]:
%pip install Pillow

Collecting Pillow
  Downloading pillow-12.1.1-cp312-cp312-win_amd64.whl.metadata (9.0 kB)
Downloading pillow-12.1.1-cp312-cp312-win_amd64.whl (7.0 MB)
   ---------------------------------------- 0.0/7.0 MB ? eta -:--:--
   - -------------------------------------- 0.2/7.0 MB 5.4 MB/s eta 0:00:02
   - -------------------------------------- 0.3/7.0 MB 4.1 MB/s eta 0:00:02
   --- ------------------------------------ 0.5/7.0 MB 4.2 MB/s eta 0:00:02
   --- ------------------------------------ 0.6/7.0 MB 3.7 MB/s eta 0:00:02
   ---- ----------------------------------- 0.8/7.0 MB 3.4 MB/s eta 0:00:02
   ----- ---------------------------------- 0.9/7.0 MB 3.3 MB/s eta 0:00:02
   ----- ---------------------------------- 1.0/7.0 MB 3.1 MB/s eta 0:00:02
   ------ --------------------------------- 1.1/7.0 MB 3.0 MB/s eta 0:00:02
   ------ --------------------------------- 1.2/7.0 MB 3.0 MB/s eta 0:00:02
   ------- -------------------------------- 1.3/7.0 MB 2.9 MB/s eta 0:00:02
   -------- ------------------------------- 1.4/7.0 MB 2.9 MB/s eta 0:00:02
   -------- ------------------------------- 1.5/7.0 MB 2.9 MB/s eta 0:00:02
   --------- ------------------------------ 1.7/7.0 MB 2.8 MB/s eta 0:00:02
   ---------- ----------------------------- 1.8/7.0 MB 2.8 MB/s eta 0:00:02
   ---------- ----------------------------- 1.9/7.0 MB 2.8 MB/s eta 0:00:02
   ----------- ---------------------------- 2.0/7.0 MB 2.8 MB/s eta 0:00:02
   ----------- ---------------------------- 2.1/7.0 MB 2.7 MB/s eta 0:00:02
   ------------ --------------------------- 2.2/7.0 MB 2.7 MB/s eta 0:00:02
   ------------- -------------------------- 2.3/7.0 MB 2.7 MB/s eta 0:00:02
   ------------- -------------------------- 2.5/7.0 MB 2.7 MB/s eta 0:00:02
   -------------- ------------------------- 2.5/7.0 MB 2.7 MB/s eta 0:00:02
   --------------- ------------------------ 2.7/7.0 MB 2.7 MB/s eta 0:00:02
   --------------- ------------------------ 2.8/7.0 MB 2.7 MB/s eta 0:00:02
   ---------------- ----------------------- 2.9/7.0 MB 2.6 MB/s eta 0:00:02
   ----------------- ---------------------- 3.0/7.0 MB 2.6 MB/s eta 0:00:02
   ----------------- ---------------------- 3.1/7.0 MB 2.6 MB/s eta 0:00:02
   ------------------ --------------------- 3.2/7.0 MB 2.6 MB/s eta 0:00:02
   ------------------ --------------------- 3.3/7.0 MB 2.6 MB/s eta 0:00:02
   ------------------- -------------------- 3.5/7.0 MB 2.6 MB/s eta 0:00:02
   -------------------- ------------------- 3.6/7.0 MB 2.6 MB/s eta 0:00:02
   -------------------- ------------------- 3.7/7.0 MB 2.6 MB/s eta 0:00:02
   --------------------- ------------------ 3.8/7.0 MB 2.6 MB/s eta 0:00:02
   ---------------------- ----------------- 3.9/7.0 MB 2.6 MB/s eta 0:00:02
   ---------------------- ----------------- 4.0/7.0 MB 2.6 MB/s eta 0:00:02
   ----------------------- ---------------- 4.1/7.0 MB 2.6 MB/s eta 0:00:02
   ------------------------ --------------- 4.2/7.0 MB 2.6 MB/s eta 0:00:02
   ------------------------ --------------- 4.4/7.0 MB 2.6 MB/s eta 0:00:02
   ------------------------- -------------- 4.5/7.0 MB 2.6 MB/s eta 0:00:02
   ------------------------- -------------- 4.6/7.0 MB 2.6 MB/s eta 0:00:01
   -------------------------- ------------- 4.7/7.0 MB 2.6 MB/s eta 0:00:01
   --------------------------- ------------ 4.8/7.0 MB 2.6 MB/s eta 0:00:01
   --------------------------- ------------ 4.9/7.0 MB 2.6 MB/s eta 0:00:01
   ---------------------------- ----------- 5.0/7.0 MB 2.5 MB/s eta 0:00:01
   ----------------------------- ---------- 5.1/7.0 MB 2.6 MB/s eta 0:00:01
   ----------------------------- ---------- 5.2/7.0 MB 2.6 MB/s eta 0:00:01
   ------------------------------ --------- 5.3/7.0 MB 2.5 MB/s eta 0:00:01
   ------------------------------- -------- 5.5/7.0 MB 2.5 MB/s eta 0:00:01
   ------------------------------- -------- 5.6/7.0 MB 2.5 MB/s eta 0:00:01
   -------------------------------- ------- 5.7/7.0 MB 2.5 MB/s eta 0:00:01
   --------------------------------- ------ 5.8/7.0 MB 2.5 MB/s eta 0:00:01
   --------------------------------- ------ 5.9/7.0 MB 2.5 MB/s eta 0:00:01
   ---------------------------------- ----- 6.0/7.0 MB 2.5 MB/s eta 0:00:01
   ----------------------------------- ---- 6.2/7.0 MB 2.5 MB/s eta 0:00:01
   ----------------------------------- ---- 6.3/7.0 MB 2.5 MB/s eta 0:00:01
   ------------------------------------ --- 6.4/7.0 MB 2.5 MB/s eta 0:00:01
   ------------------------------------ --- 6.5/7.0 MB 2.5 MB/s eta 0:00:01
   ------------------------------------- -- 6.6/7.0 MB 2.5 MB/s eta 0:00:01
   -------------------------------------- - 6.7/7.0 MB 2.5 MB/s eta 0:00:01
   -------------------------------------- - 6.8/7.0 MB 2.5 MB/s eta 0:00:01
   ---------------------------------------  6.9/7.0 MB 2.5 MB/s eta 0:00:01
   ---------------------------------------  7.0/7.0 MB 2.5 MB/s eta 0:00:01
   ---------------------------------------- 7.0/7.0 MB 2.5 MB/s eta 0:00:00
Installing collected packages: Pillow
Successfully installed Pillow-12.1.1
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
!pip install requests

'pip' is not recognized as an internal or external command,
operable program or batch file.

In [5]:
%pip install --upgrade selenium

Requirement already satisfied: selenium in c:\users\tipqc\appdata\local\programs\python\python312\lib\site-packages (4.40.0)
Collecting selenium
  Downloading selenium-4.41.0-py3-none-any.whl.metadata (7.5 kB)
Requirement already satisfied: certifi>=2026.1.4 in c:\users\tipqc\appdata\local\programs\python\python312\lib\site-packages (from selenium) (2026.1.4)
Requirement already satisfied: trio<1.0,>=0.31.0 in c:\users\tipqc\appdata\local\programs\python\python312\lib\site-packages (from selenium) (0.33.0)
Requirement already satisfied: trio-websocket<1.0,>=0.12.2 in c:\users\tipqc\appdata\local\programs\python\python312\lib\site-packages (from selenium) (0.12.2)
Requirement already satisfied: typing_extensions<5.0,>=4.15.0 in c:\users\tipqc\appdata\local\programs\python\python312\lib\site-packages (from selenium) (4.15.0)
Requirement already satisfied: urllib3<3.0,>=2.6.3 in c:\users\tipqc\appdata\local\programs\python\python312\lib\site-packages (from urllib3[socks]<3.0,>=2.6.3->selenium) (2.6.3)
Requirement already satisfied: websocket-client<2.0,>=1.8.0 in c:\users\tipqc\appdata\local\programs\python\python312\lib\site-packages (from selenium) (1.9.0)
Requirement already satisfied: attrs>=23.2.0 in c:\users\tipqc\appdata\local\programs\python\python312\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (25.4.0)
Requirement already satisfied: sortedcontainers in c:\users\tipqc\appdata\local\programs\python\python312\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (2.4.0)
Requirement already satisfied: idna in c:\users\tipqc\appdata\local\programs\python\python312\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (3.11)
Requirement already satisfied: outcome in c:\users\tipqc\appdata\local\programs\python\python312\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in c:\users\tipqc\appdata\local\programs\python\python312\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (1.3.1)
Requirement already satisfied: cffi>=1.14 in c:\users\tipqc\appdata\local\programs\python\python312\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (2.0.0)
Requirement already satisfied: wsproto>=0.14 in c:\users\tipqc\appdata\local\programs\python\python312\lib\site-packages (from trio-websocket<1.0,>=0.12.2->selenium) (1.3.2)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in c:\users\tipqc\appdata\local\programs\python\python312\lib\site-packages (from urllib3[socks]<3.0,>=2.6.3->selenium) (1.7.1)
Requirement already satisfied: pycparser in c:\users\tipqc\appdata\local\programs\python\python312\lib\site-packages (from cffi>=1.14->trio<1.0,>=0.31.0->selenium) (3.0)
Requirement already satisfied: h11<1,>=0.16.0 in c:\users\tipqc\appdata\local\programs\python\python312\lib\site-packages (from wsproto>=0.14->trio-websocket<1.0,>=0.12.2->selenium) (0.16.0)
Downloading selenium-4.41.0-py3-none-any.whl (9.5 MB)
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.5 MB 10.9 MB/s eta 0:00:01
   - -------------------------------------- 0.4/9.5 MB 5.3 MB/s eta 0:00:02
   -- ------------------------------------- 0.6/9.5 MB 4.6 MB/s eta 0:00:02
   -- ------------------------------------- 0.7/9.5 MB 4.0 MB/s eta 0:00:03
   --- ------------------------------------ 0.8/9.5 MB 3.6 MB/s eta 0:00:03
   --- ------------------------------------ 0.9/9.5 MB 3.4 MB/s eta 0:00:03
   ---- ----------------------------------- 1.0/9.5 MB 3.2 MB/s eta 0:00:03
   ---- ----------------------------------- 1.1/9.5 MB 3.1 MB/s eta 0:00:03
   ----- ---------------------------------- 1.2/9.5 MB 3.1 MB/s eta 0:00:03
   ----- ---------------------------------- 1.4/9.5 MB 3.0 MB/s eta 0:00:03
   ------ --------------------------------- 1.5/9.5 MB 2.9 MB/s eta 0:00:03
   ------ --------------------------------- 1.6/9.5 MB 2.9 MB/s eta 0:00:03
   ------- -------------------------------- 1.7/9.5 MB 2.8 MB/s eta 0:00:03
   ------- -------------------------------- 1.8/9.5 MB 2.9 MB/s eta 0:00:03
   -------- ------------------------------- 1.9/9.5 MB 2.8 MB/s eta 0:00:03
   -------- ------------------------------- 2.0/9.5 MB 2.8 MB/s eta 0:00:03
   --------- ------------------------------ 2.2/9.5 MB 2.7 MB/s eta 0:00:03
   --------- ------------------------------ 2.3/9.5 MB 2.7 MB/s eta 0:00:03
   ---------- ----------------------------- 2.4/9.5 MB 2.8 MB/s eta 0:00:03
   ---------- ----------------------------- 2.5/9.5 MB 2.7 MB/s eta 0:00:03
   ---------- ----------------------------- 2.6/9.5 MB 2.7 MB/s eta 0:00:03
   ----------- ---------------------------- 2.7/9.5 MB 2.7 MB/s eta 0:00:03
   ----------- ---------------------------- 2.8/9.5 MB 2.7 MB/s eta 0:00:03
   ------------ --------------------------- 2.9/9.5 MB 2.7 MB/s eta 0:00:03
   ------------ --------------------------- 3.1/9.5 MB 2.7 MB/s eta 0:00:03
   ------------- -------------------------- 3.2/9.5 MB 2.6 MB/s eta 0:00:03
   ------------- -------------------------- 3.3/9.5 MB 2.6 MB/s eta 0:00:03
   -------------- ------------------------- 3.4/9.5 MB 2.6 MB/s eta 0:00:03
   -------------- ------------------------- 3.5/9.5 MB 2.6 MB/s eta 0:00:03
   --------------- ------------------------ 3.6/9.5 MB 2.6 MB/s eta 0:00:03
   --------------- ------------------------ 3.7/9.5 MB 2.6 MB/s eta 0:00:03
   ---------------- ----------------------- 3.8/9.5 MB 2.6 MB/s eta 0:00:03
   ---------------- ----------------------- 3.9/9.5 MB 2.6 MB/s eta 0:00:03
   ----------------- ---------------------- 4.1/9.5 MB 2.6 MB/s eta 0:00:03
   ----------------- ---------------------- 4.2/9.5 MB 2.6 MB/s eta 0:00:03
   ------------------ --------------------- 4.3/9.5 MB 2.6 MB/s eta 0:00:03
   ------------------ --------------------- 4.4/9.5 MB 2.6 MB/s eta 0:00:02
   ------------------ --------------------- 4.5/9.5 MB 2.6 MB/s eta 0:00:02
   ------------------- -------------------- 4.6/9.5 MB 2.6 MB/s eta 0:00:02
   ------------------- -------------------- 4.7/9.5 MB 2.6 MB/s eta 0:00:02
   -------------------- ------------------- 4.9/9.5 MB 2.6 MB/s eta 0:00:02
   -------------------- ------------------- 5.0/9.5 MB 2.6 MB/s eta 0:00:02
   --------------------- ------------------ 5.1/9.5 MB 2.6 MB/s eta 0:00:02
   --------------------- ------------------ 5.2/9.5 MB 2.6 MB/s eta 0:00:02
   ---------------------- ----------------- 5.3/9.5 MB 2.6 MB/s eta 0:00:02
   ---------------------- ----------------- 5.4/9.5 MB 2.6 MB/s eta 0:00:02
   ----------------------- ---------------- 5.6/9.5 MB 2.6 MB/s eta 0:00:02
   ----------------------- ---------------- 5.7/9.5 MB 2.6 MB/s eta 0:00:02
   ------------------------ --------------- 5.8/9.5 MB 2.6 MB/s eta 0:00:02
   ------------------------ --------------- 5.9/9.5 MB 2.6 MB/s eta 0:00:02
   ------------------------- -------------- 6.0/9.5 MB 2.6 MB/s eta 0:00:02
   ------------------------- -------------- 6.1/9.5 MB 2.6 MB/s eta 0:00:02
   -------------------------- ------------- 6.2/9.5 MB 2.5 MB/s eta 0:00:02
   -------------------------- ------------- 6.3/9.5 MB 2.5 MB/s eta 0:00:02
   --------------------------- ------------ 6.5/9.5 MB 2.5 MB/s eta 0:00:02
   --------------------------- ------------ 6.6/9.5 MB 2.5 MB/s eta 0:00:02
   ---------------------------- ----------- 6.7/9.5 MB 2.5 MB/s eta 0:00:02
   ---------------------------- ----------- 6.8/9.5 MB 2.5 MB/s eta 0:00:02
   ---------------------------- ----------- 6.9/9.5 MB 2.5 MB/s eta 0:00:02
   ----------------------------- ---------- 7.0/9.5 MB 2.5 MB/s eta 0:00:01
   ----------------------------- ---------- 7.1/9.5 MB 2.5 MB/s eta 0:00:01
   ------------------------------ --------- 7.2/9.5 MB 2.5 MB/s eta 0:00:01
   ------------------------------ --------- 7.4/9.5 MB 2.5 MB/s eta 0:00:01
   ------------------------------- -------- 7.5/9.5 MB 2.5 MB/s eta 0:00:01
   ------------------------------- -------- 7.6/9.5 MB 2.5 MB/s eta 0:00:01
   -------------------------------- ------- 7.7/9.5 MB 2.5 MB/s eta 0:00:01
   -------------------------------- ------- 7.8/9.5 MB 2.5 MB/s eta 0:00:01
   --------------------------------- ------ 7.9/9.5 MB 2.5 MB/s eta 0:00:01
   --------------------------------- ------ 8.0/9.5 MB 2.5 MB/s eta 0:00:01
   ---------------------------------- ----- 8.1/9.5 MB 2.5 MB/s eta 0:00:01
   ---------------------------------- ----- 8.3/9.5 MB 2.5 MB/s eta 0:00:01
   ----------------------------------- ---- 8.4/9.5 MB 2.5 MB/s eta 0:00:01
   ----------------------------------- ---- 8.5/9.5 MB 2.5 MB/s eta 0:00:01
   ------------------------------------ --- 8.6/9.5 MB 2.5 MB/s eta 0:00:01
   ------------------------------------ --- 8.7/9.5 MB 2.5 MB/s eta 0:00:01
   ------------------------------------ --- 8.8/9.5 MB 2.5 MB/s eta 0:00:01
   ------------------------------------- -- 8.9/9.5 MB 2.5 MB/s eta 0:00:01
   ------------------------------------- -- 9.0/9.5 MB 2.5 MB/s eta 0:00:01
   -------------------------------------- - 9.1/9.5 MB 2.5 MB/s eta 0:00:01
   -------------------------------------- - 9.2/9.5 MB 2.5 MB/s eta 0:00:01
   ---------------------------------------  9.4/9.5 MB 2.5 MB/s eta 0:00:01
   ---------------------------------------  9.5/9.5 MB 2.5 MB/s eta 0:00:01
   ---------------------------------------- 9.5/9.5 MB 2.5 MB/s eta 0:00:00
Installing collected packages: selenium
  Attempting uninstall: selenium
    Found existing installation: selenium 4.40.0
    Uninstalling selenium-4.40.0:
      Successfully uninstalled selenium-4.40.0
Successfully installed selenium-4.41.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [10]:
import os
import time
import requests
import io
from PIL import Image
from selenium import webdriver
from selenium.webdriver.firefox.options import Options
from selenium.webdriver.common.by import By


print("Setting up browser...")

# 1. Clean Local Setup (No Headless, No Colab stuff)
options = Options()
# 2. Add your custom User-Agent header (Firefox uses 'set_preference' for this)
user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:123.0) Gecko/20100101 Firefox/123.0"
options.set_preference("general.useragent.override", user_agent)


driver = webdriver.Firefox(options=options)

Setting up browser...

In [11]:

def scroll_to_end(driver):
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    time.sleep(5) 

def getImageUrls(name, totalImgs, driver):
    search_url = "https://www.google.com/search?q={q}&tbm=isch"
    driver.get(search_url.format(q=name))
    img_urls = set()
    img_count = 0
    results_start = 0
    
    while(img_count < totalImgs):
        #scroll_to_end(driver)
        # CHANGED: Options.XPATH back to By.XPATH
        thumbnail_results = driver.find_elements(By.XPATH, "//img[contains(@class, 'YQ4gaf')]")
        totalResults = len(thumbnail_results)
        print(f"Found: {totalResults} search results. Extracting links from {results_start}: {totalResults}")
        
        for img in thumbnail_results[results_start: totalResults]:
            try:
                img.click()
                time.sleep(2)
            except Exception:
                continue
                
            # CHANGED: Options.CSS_SELECTOR back to By.CSS_SELECTOR
            actual_images = driver.find_elements(By.CSS_SELECTOR, 'img.iPVvYb, img.sFlh5c, img.n3VNCb')
            for actual_image in actual_images:
                if actual_image.get_attribute('src') and 'https' in actual_image.get_attribute('src'):
                    img_urls.add(actual_image.get_attribute('src'))
                    
            img_count = len(img_urls)
            if img_count >= totalImgs:
                print(f"Found: {img_count} image links")
                break
        else:
            print("Found:", img_count, "looking for more image links ...")
            try:
                # CHANGED: Options.CSS_SELECTOR back to By.CSS_SELECTOR
                load_more_button = driver.find_element(By.CSS_SELECTOR, ".mye4qd")
                driver.execute_script("document.querySelector('.mye4qd').click();")
            except Exception:
                pass
        results_start = len(thumbnail_results)
    return img_urls

def downloadImages(folder_path, file_name, url):
    try:
        image_content = requests.get(url).content
    except Exception as e:
        print(f"ERROR COULD NOT DOWNLOAD {url} {e}")
        return 
        
    try:
        image_file = io.BytesIO(image_content)
        image = Image.open(image_file).convert('RGB')
        file_path = os.path.join(folder_path, file_name)
        with open(file_path, 'wb') as f:
            image.save(f, "JPEG", quality=85)
        print(f"SAVED {url} AT: {file_path}")
    except Exception as e:
        print(f"ERROR COULD NOT SAVE {url} - {e}")

def saveInDestFolder(searchNames, destDir, totalImgs, driver):
    for name in list(searchNames):
        path = os.path.join(destDir, name)
        if not os.path.isdir(path):
            os.makedirs(path)
        print('Current Path:', path)
        
        totalLinks = getImageUrls(name, totalImgs, driver)
        print('totalLinks found:', len(totalLinks))
        
        if totalLinks is None or len(totalLinks) == 0:
            print('Images not found for', name)
        else:
            for i, link in enumerate(totalLinks):
                file_name = f"image_{i:03}.jpg" 
                downloadImages(path, file_name, link)

# --- Execution ---
searchNames = ['cat']
destDir = './Dataset/'
totalImgs = 5

try:
    saveInDestFolder(searchNames, destDir, totalImgs, driver)
finally:
    driver.quit()
    print("Browser closed. Script finished.")

Current Path: ./Dataset/cat
Found: 216 search results. Extracting links from 0: 216
Found: 5 image links
totalLinks found: 5
ERROR COULD NOT SAVE https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Cat_November_2010-1a.jpg/960px-Cat_November_2010-1a.jpg - cannot identify image file <_io.BytesIO object at 0x0000021A6B6A6A20>
SAVED https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT74p0-GFNquBzzGLN9SazH22Wrus46aPPqYQ&s AT: ./Dataset/cat\image_001.jpg
SAVED https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzTojBf4VJCGR4Z-QxG-7GozKDuWjCst6z6Q&s AT: ./Dataset/cat\image_002.jpg
SAVED https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQxMMWd08C5AE2EXAyUKJ_5SLvDntWHayN0uA&s AT: ./Dataset/cat\image_003.jpg
SAVED https://i.natgeofe.com/n/548467d8-c5f1-4551-9f58-6817a8d2c45e/NationalGeographic_2572187_16x9.jpg?w=1200 AT: ./Dataset/cat\image_004.jpg
Browser closed. Script finished.

# Web Scraping of Movies Information using BeautifulSoup

We want to analyze the distributions of IMDB and Metacritic movie ratings to see if we find anything interesting. To do this, we'll first scrape data for over 2000 movies.

In [19]:
from requests import get
url = 'https://www.imdb.com/search/title?release_date=2017&sort=num_votes,desc&page=1'
response = get(url)
print(response.text[:500])

Using BeautifulSoup to parse the HTML content
To parse our HTML document and extract the 50 div containers, weʼll use a Python module called BeautifulSoup, the most common web scraping module for Python.
In the following code cell we will:
* Import the BeautifulSoup class creator from the package bs4.
* Parse response. text by creating a BeautifulSoup object, and assign this object to html_soup. The 'html.parser' argument indicates that we want to do the parsing using
Pythonʼ s built-in HTML parser .

In [39]:
from selenium import webdriver
from selenium.webdriver.firefox.options import Options
from selenium.webdriver.common.by import By
from bs4 import BeautifulSoup
import time

print("Starting Firefox...")
options = Options()

# 1. Dress up like a normal human browser
user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:123.0) Gecko/20100101 Firefox/123.0"
options.set_preference("general.useragent.override", user_agent)

driver = webdriver.Firefox(options=options)
url = 'https://www.imdb.com/search/title/?release_date=2017-01-01,2017-12-31&sort=num_votes,desc'

try:
    print("Loading IMDb page...")
    driver.get(url)
    
    print("Scrolling down to load more movies...")
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    time.sleep(3) 
    

    '''try:
        load_more_btn = driver.find_element(By.CSS_SELECTOR, "button.ipc-see-more__button")
        driver.execute_script("arguments[0].click();", load_more_btn)
        print("Clicked 'Load More' button!")
        time.sleep(3)
    except:
        pass # If there is no button, just ignore and keep going'''
        
    # 3. The page is now fully loaded! Grab the raw HTML from Selenium
    print("Grabbing the fully loaded HTML...")
    html = driver.page_source
    
    # 4. Hand the HTML over to BeautifulSoup to do the reading
    html_soup = BeautifulSoup(html, 'html.parser')
    movie_containers = html_soup.find_all('li', class_='ipc-metadata-list-summary-item')
    
    print("-------------------------")
    print("Movies found:", len(movie_containers))
    print("-------------------------")
    
finally:
    # We have our HTML, so we don't need the browser anymore!
    driver.quit()
    print("Browser closed.")

Starting Firefox...
Loading IMDb page...
Scrolling down to load more movies...
Grabbing the fully loaded HTML...
-------------------------
Movies found: 50
-------------------------
Browser closed.

In [40]:
movie_containers = html_soup.find_all('li', class_='ipc-metadata-list-summary-item')
print(type(movie_containers))
print(len(movie_containers))

<class 'bs4.element.ResultSet'>
50

movie_containers = html_soup.find_all('div', class_ = 'lister-item mode-advanced')
print(type(movie_containers))
print(len(movie_containers))

In [55]:
first_movie = movie_containers[0]
first_movie

<li class="ipc-metadata-list-summary-item"><div class="ipc-metadata-list-summary-item__c"><div class="ipc-metadata-list-summary-item__tc"><span aria-disabled="false" class="ipc-metadata-list-summary-item__t ipc-btn--not-interactable"></span><div class="sc-fc35a1ef-1 lmHCrT dli-parent"><div class="sc-fc35a1ef-0 hTMtRz"><div class="sc-d0224b4e-0 jfogmY dli-poster-container"><div class="ipc-poster ipc-poster--base ipc-poster--media-radius ipc-poster--wl-true ipc-poster--dynamic-width ipc-sub-grid-item ipc-sub-grid-item--span-2" role="group"><div class="ipc-media ipc-media--poster-27x40 ipc-image-media-ratio--poster-27x40 ipc-media--media-radius ipc-media--base ipc-media--poster-s ipc-poster__poster-image ipc-media__img" style="width:100%"><img alt="Hugh Jackman in Logan (2017)" class="ipc-image" loading="lazy" sizes="50vw, (min-width: 480px) 34vw, (min-width: 600px) 26vw, (min-width: 1024px) 16vw, (min-width: 1280px) 16vw" src="https://m.media-amazon.com/images/M/MV5BM2JjODdkMGMtNmY2YS00OGM2LThiY2YtZGYyNzE4Nzc2ODA0XkEyXkFqcGc@._V1_QL75_UX90_CR0,1,90,133_.jpg" srcset="https://m.media-amazon.com/images/M/MV5BM2JjODdkMGMtNmY2YS00OGM2LThiY2YtZGYyNzE4Nzc2ODA0XkEyXkFqcGc@._V1_QL75_UX90_CR0,1,90,133_.jpg 90w, https://m.media-amazon.com/images/M/MV5BM2JjODdkMGMtNmY2YS00OGM2LThiY2YtZGYyNzE4Nzc2ODA0XkEyXkFqcGc@._V1_QL75_UX135_CR0,2,135,200_.jpg 135w, https://m.media-amazon.com/images/M/MV5BM2JjODdkMGMtNmY2YS00OGM2LThiY2YtZGYyNzE4Nzc2ODA0XkEyXkFqcGc@._V1_QL75_UX180_CR0,2,180,266_.jpg 180w" width="90"/></div><div aria-label="Add to Watchlist" aria-pressed="false" class="ipc-watchlist-ribbon ipc-focusable ipc-watchlist-ribbon--m ipc-watchlist-ribbon--base ipc-watchlist-ribbon--onImage ipc-poster__watchlist-ribbon" data-testid="poster-watchlist-ribbon-add" role="button" tabindex="0"><svg class="ipc-watchlist-ribbon__bg" height="34px" role="presentation" viewbox="0 0 24 34" width="24px" xmlns="http://www.w3.org/2000/svg"><polygon class="ipc-watchlist-ribbon__bg-ribbon" fill="#000000" points="24 0 0 0 0 32 12.2436611 26.2926049 24 31.7728343"></polygon><polygon class="ipc-watchlist-ribbon__bg-hover" points="24 0 0 0 0 32 12.2436611 26.2926049 24 31.7728343"></polygon><polygon class="ipc-watchlist-ribbon__bg-shadow" points="24 31.7728343 24 33.7728343 12.2436611 28.2926049 0 34 0 32 12.2436611 26.2926049"></polygon></svg><div class="ipc-watchlist-ribbon__icon" role="presentation"><svg class="ipc-icon ipc-icon--add ipc-icon--inline" fill="currentColor" height="24" role="presentation" viewbox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg"><path d="M18 13h-5v5c0 .55-.45 1-1 1s-1-.45-1-1v-5H6c-.55 0-1-.45-1-1s.45-1 1-1h5V6c0-.55.45-1 1-1s1 .45 1 1v5h5c.55 0 1 .45 1 1s-.45 1-1 1z"></path></svg></div></div><a aria-label="View title page for Logan" class="ipc-lockup-overlay ipc-focusable ipc-focusable--constrained" href="/title/tt3315342/?ref_=sr_i_1"><div class="ipc-lockup-overlay__screen"></div></a></div></div><div class="sc-a55f6282-0 lmJvqs"><div class="ipc-title ipc-title--base ipc-title--title ipc-title-link-no-icon ipc-title--on-textPrimary sc-87337ed2-2 dRlLYG dli-title with-margin"><a class="ipc-title-link-wrapper" href="/title/tt3315342/?ref_=sr_t_1" tabindex="0"><h3 class="ipc-title__text">1. Logan</h3></a></div><div class="sc-a55f6282-5 bhUIDq dli-title-metadata"><span class="sc-a55f6282-6 iMumIM dli-title-metadata-item">2017</span><span class="sc-a55f6282-6 iMumIM dli-title-metadata-item">2h 17m</span><span class="sc-a55f6282-6 iMumIM dli-title-metadata-item">R</span><span class="sc-a55f6282-8 gdLTlA"><span class="sc-9fe7b0ef-0 hDuMnh metacritic-score-box" style="background-color:#54A72A">77</span><span class="metacritic-score-label">Metascore</span></span></div><span class="sc-a55f6282-1 ddtLhl"><div class="sc-17ce9e4b-0 ddMjUi sc-a55f6282-2 bxNDyb dli-ratings-container" data-testid="ratingGroup--container"><span aria-label="IMDb rating: 8.1" class="ipc-rating-star ipc-rating-star--base ipc-rating-star--imdb ratingGroup--imdb-rating" data-testid="ratingGroup--imdb-rating"><svg class="ipc-icon ipc-icon--star-inline" fill="currentColor" height="24" role="presentation" viewbox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg"><path d="M12 20.1l5.82 3.682c1.066.675 2.37-.322 2.09-1.584l-1.543-6.926 5.146-4.667c.94-.85.435-2.465-.799-2.567l-6.773-.602L13.29.89a1.38 1.38 0 0 0-2.581 0l-2.65 6.53-6.774.602C.052 8.126-.453 9.74.486 10.59l5.147 4.666-1.542 6.926c-.28 1.262 1.023 2.26 2.09 1.585L12 20.099z"></path></svg><span class="ipc-rating-star--rating">8.1</span><span class="ipc-rating-star--voteCount"> (<!-- -->919K<!-- -->)</span></span><button aria-label="Rate Logan" class="ipc-rate-button sc-17ce9e4b-1 flqkCx ratingGroup--user-rating ipc-rate-button--unrated ipc-rate-button--base" data-testid="rate-button"><span class="ipc-rating-star ipc-rating-star--base ipc-rating-star--rate"><svg class="ipc-icon ipc-icon--star-border-inline" fill="currentColor" height="24" role="presentation" viewbox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg"><path d="M22.724 8.217l-6.786-.587-2.65-6.22c-.477-1.133-2.103-1.133-2.58 0l-2.65 6.234-6.772.573c-1.234.098-1.739 1.636-.8 2.446l5.146 4.446-1.542 6.598c-.28 1.202 1.023 2.153 2.09 1.51l5.818-3.495 5.819 3.509c1.065.643 2.37-.308 2.089-1.51l-1.542-6.612 5.145-4.446c.94-.81.45-2.348-.785-2.446zm-10.726 8.89l-5.272 3.174 1.402-5.983-4.655-4.026 6.141-.531 2.384-5.634 2.398 5.648 6.14.531-4.654 4.026 1.402 5.983-5.286-3.187z"></path></svg><span class="ipc-rating-star--rate">Rate</span></span></button></div><button aria-disabled="false" aria-label="Mark Logan as watched" aria-pressed="false" class="ipc-btn ipc-btn--half-padding ipc-btn--left-align-content ipc-btn--default-height ipc-btn--core-base ipc-btn--theme-base ipc-btn--button-radius ipc-btn--on-accent2 ipc-text-button sc-43529d24-0 jmjwiI sc-a55f6282-3 cJURAI" data-testid="inline-watched-button-tt3315342" tabindex="0"><svg class="ipc-icon ipc-icon--visibility ipc-btn__icon ipc-btn__icon--pre watched-button--icon ipc-btn__icon--disable-margin" fill="currentColor" height="24" role="presentation" viewbox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg"><path d="M0 0h24v24H0V0z" fill="none"></path><path d="M12 6c3.79 0 7.17 2.13 8.82 5.5C19.17 14.87 15.79 17 12 17s-7.17-2.13-8.82-5.5C4.83 8.13 8.21 6 12 6m0-2C7 4 2.73 7.11 1 11.5 2.73 15.89 7 19 12 19s9.27-3.11 11-7.5C21.27 7.11 17 4 12 4zm0 5c1.38 0 2.5 1.12 2.5 2.5S13.38 14 12 14s-2.5-1.12-2.5-2.5S10.62 9 12 9m0-2c-2.48 0-4.5 2.02-4.5 4.5S9.52 16 12 16s4.5-2.02 4.5-4.5S14.48 7 12 7z"></path></svg><span class="ipc-btn__text">Mark as watched</span></button></span></div><div class="sc-fc35a1ef-2 ejpVMt dli-post-element"><button aria-disabled="false" aria-label="See more information about Logan" class="ipc-icon-button li-info-icon ipc-icon-button--base ipc-icon-button--onAccent2" data-testid="title-summary-prompt-button-info-icon" tabindex="0" title="See more information about Logan"><svg class="ipc-icon ipc-icon--info" fill="currentColor" height="24" role="presentation" viewbox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg"><path d="M0 0h24v24H0V0z" fill="none"></path><path d="M11 7h2v2h-2zm0 4h2v6h-2zm1-9C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm0 18c-4.41 0-8-3.59-8-8s3.59-8 8-8 8 3.59 8 8-3.59 8-8 8z"></path></svg></button></div></div><div class="sc-9d52d06f-1 bDNbpf"><div class="ipc-html-content ipc-html-content--base sc-9d52d06f-0 bVMrTF title-description-plot-container" role="presentation"><div class="ipc-html-content-inner-div" role="presentation">In a future where mutants are nearly extinct, an elderly and weary Logan leads a quiet life. But when Laura, a mutant child pursued by scientists, comes to him for help, he must get her to safety.</div></div></div></div></div></div></li>

In [44]:
first_movie.div

<div class="ipc-metadata-list-summary-item__c"><div class="ipc-metadata-list-summary-item__tc"><span aria-disabled="false" class="ipc-metadata-list-summary-item__t ipc-btn--not-interactable"></span><div class="sc-fc35a1ef-1 lmHCrT dli-parent"><div class="sc-fc35a1ef-0 hTMtRz"><div class="sc-d0224b4e-0 jfogmY dli-poster-container"><div class="ipc-poster ipc-poster--base ipc-poster--media-radius ipc-poster--wl-true ipc-poster--dynamic-width ipc-sub-grid-item ipc-sub-grid-item--span-2" role="group"><div class="ipc-media ipc-media--poster-27x40 ipc-image-media-ratio--poster-27x40 ipc-media--media-radius ipc-media--base ipc-media--poster-s ipc-poster__poster-image ipc-media__img" style="width:100%"><img alt="Hugh Jackman in Logan (2017)" class="ipc-image" loading="lazy" sizes="50vw, (min-width: 480px) 34vw, (min-width: 600px) 26vw, (min-width: 1024px) 16vw, (min-width: 1280px) 16vw" src="https://m.media-amazon.com/images/M/MV5BM2JjODdkMGMtNmY2YS00OGM2LThiY2YtZGYyNzE4Nzc2ODA0XkEyXkFqcGc@._V1_QL75_UX90_CR0,1,90,133_.jpg" srcset="https://m.media-amazon.com/images/M/MV5BM2JjODdkMGMtNmY2YS00OGM2LThiY2YtZGYyNzE4Nzc2ODA0XkEyXkFqcGc@._V1_QL75_UX90_CR0,1,90,133_.jpg 90w, https://m.media-amazon.com/images/M/MV5BM2JjODdkMGMtNmY2YS00OGM2LThiY2YtZGYyNzE4Nzc2ODA0XkEyXkFqcGc@._V1_QL75_UX135_CR0,2,135,200_.jpg 135w, https://m.media-amazon.com/images/M/MV5BM2JjODdkMGMtNmY2YS00OGM2LThiY2YtZGYyNzE4Nzc2ODA0XkEyXkFqcGc@._V1_QL75_UX180_CR0,2,180,266_.jpg 180w" width="90"/></div><div aria-label="Add to Watchlist" aria-pressed="false" class="ipc-watchlist-ribbon ipc-focusable ipc-watchlist-ribbon--m ipc-watchlist-ribbon--base ipc-watchlist-ribbon--onImage ipc-poster__watchlist-ribbon" data-testid="poster-watchlist-ribbon-add" role="button" tabindex="0"><svg class="ipc-watchlist-ribbon__bg" height="34px" role="presentation" viewbox="0 0 24 34" width="24px" xmlns="http://www.w3.org/2000/svg"><polygon class="ipc-watchlist-ribbon__bg-ribbon" fill="#000000" points="24 0 0 0 0 32 12.2436611 26.2926049 24 31.7728343"></polygon><polygon class="ipc-watchlist-ribbon__bg-hover" points="24 0 0 0 0 32 12.2436611 26.2926049 24 31.7728343"></polygon><polygon class="ipc-watchlist-ribbon__bg-shadow" points="24 31.7728343 24 33.7728343 12.2436611 28.2926049 0 34 0 32 12.2436611 26.2926049"></polygon></svg><div class="ipc-watchlist-ribbon__icon" role="presentation"><svg class="ipc-icon ipc-icon--add ipc-icon--inline" fill="currentColor" height="24" role="presentation" viewbox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg"><path d="M18 13h-5v5c0 .55-.45 1-1 1s-1-.45-1-1v-5H6c-.55 0-1-.45-1-1s.45-1 1-1h5V6c0-.55.45-1 1-1s1 .45 1 1v5h5c.55 0 1 .45 1 1s-.45 1-1 1z"></path></svg></div></div><a aria-label="View title page for Logan" class="ipc-lockup-overlay ipc-focusable ipc-focusable--constrained" href="/title/tt3315342/?ref_=sr_i_1"><div class="ipc-lockup-overlay__screen"></div></a></div></div><div class="sc-a55f6282-0 lmJvqs"><div class="ipc-title ipc-title--base ipc-title--title ipc-title-link-no-icon ipc-title--on-textPrimary sc-87337ed2-2 dRlLYG dli-title with-margin"><a class="ipc-title-link-wrapper" href="/title/tt3315342/?ref_=sr_t_1" tabindex="0"><h3 class="ipc-title__text">1. Logan</h3></a></div><div class="sc-a55f6282-5 bhUIDq dli-title-metadata"><span class="sc-a55f6282-6 iMumIM dli-title-metadata-item">2017</span><span class="sc-a55f6282-6 iMumIM dli-title-metadata-item">2h 17m</span><span class="sc-a55f6282-6 iMumIM dli-title-metadata-item">R</span><span class="sc-a55f6282-8 gdLTlA"><span class="sc-9fe7b0ef-0 hDuMnh metacritic-score-box" style="background-color:#54A72A">77</span><span class="metacritic-score-label">Metascore</span></span></div><span class="sc-a55f6282-1 ddtLhl"><div class="sc-17ce9e4b-0 ddMjUi sc-a55f6282-2 bxNDyb dli-ratings-container" data-testid="ratingGroup--container"><span aria-label="IMDb rating: 8.1" class="ipc-rating-star ipc-rating-star--base ipc-rating-star--imdb ratingGroup--imdb-rating" data-testid="ratingGroup--imdb-rating"><svg class="ipc-icon ipc-icon--star-inline" fill="currentColor" height="24" role="presentation" viewbox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg"><path d="M12 20.1l5.82 3.682c1.066.675 2.37-.322 2.09-1.584l-1.543-6.926 5.146-4.667c.94-.85.435-2.465-.799-2.567l-6.773-.602L13.29.89a1.38 1.38 0 0 0-2.581 0l-2.65 6.53-6.774.602C.052 8.126-.453 9.74.486 10.59l5.147 4.666-1.542 6.926c-.28 1.262 1.023 2.26 2.09 1.585L12 20.099z"></path></svg><span class="ipc-rating-star--rating">8.1</span><span class="ipc-rating-star--voteCount"> (<!-- -->919K<!-- -->)</span></span><button aria-label="Rate Logan" class="ipc-rate-button sc-17ce9e4b-1 flqkCx ratingGroup--user-rating ipc-rate-button--unrated ipc-rate-button--base" data-testid="rate-button"><span class="ipc-rating-star ipc-rating-star--base ipc-rating-star--rate"><svg class="ipc-icon ipc-icon--star-border-inline" fill="currentColor" height="24" role="presentation" viewbox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg"><path d="M22.724 8.217l-6.786-.587-2.65-6.22c-.477-1.133-2.103-1.133-2.58 0l-2.65 6.234-6.772.573c-1.234.098-1.739 1.636-.8 2.446l5.146 4.446-1.542 6.598c-.28 1.202 1.023 2.153 2.09 1.51l5.818-3.495 5.819 3.509c1.065.643 2.37-.308 2.089-1.51l-1.542-6.612 5.145-4.446c.94-.81.45-2.348-.785-2.446zm-10.726 8.89l-5.272 3.174 1.402-5.983-4.655-4.026 6.141-.531 2.384-5.634 2.398 5.648 6.14.531-4.654 4.026 1.402 5.983-5.286-3.187z"></path></svg><span class="ipc-rating-star--rate">Rate</span></span></button></div><button aria-disabled="false" aria-label="Mark Logan as watched" aria-pressed="false" class="ipc-btn ipc-btn--half-padding ipc-btn--left-align-content ipc-btn--default-height ipc-btn--core-base ipc-btn--theme-base ipc-btn--button-radius ipc-btn--on-accent2 ipc-text-button sc-43529d24-0 jmjwiI sc-a55f6282-3 cJURAI" data-testid="inline-watched-button-tt3315342" tabindex="0"><svg class="ipc-icon ipc-icon--visibility ipc-btn__icon ipc-btn__icon--pre watched-button--icon ipc-btn__icon--disable-margin" fill="currentColor" height="24" role="presentation" viewbox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg"><path d="M0 0h24v24H0V0z" fill="none"></path><path d="M12 6c3.79 0 7.17 2.13 8.82 5.5C19.17 14.87 15.79 17 12 17s-7.17-2.13-8.82-5.5C4.83 8.13 8.21 6 12 6m0-2C7 4 2.73 7.11 1 11.5 2.73 15.89 7 19 12 19s9.27-3.11 11-7.5C21.27 7.11 17 4 12 4zm0 5c1.38 0 2.5 1.12 2.5 2.5S13.38 14 12 14s-2.5-1.12-2.5-2.5S10.62 9 12 9m0-2c-2.48 0-4.5 2.02-4.5 4.5S9.52 16 12 16s4.5-2.02 4.5-4.5S14.48 7 12 7z"></path></svg><span class="ipc-btn__text">Mark as watched</span></button></span></div><div class="sc-fc35a1ef-2 ejpVMt dli-post-element"><button aria-disabled="false" aria-label="See more information about Logan" class="ipc-icon-button li-info-icon ipc-icon-button--base ipc-icon-button--onAccent2" data-testid="title-summary-prompt-button-info-icon" tabindex="0" title="See more information about Logan"><svg class="ipc-icon ipc-icon--info" fill="currentColor" height="24" role="presentation" viewbox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg"><path d="M0 0h24v24H0V0z" fill="none"></path><path d="M11 7h2v2h-2zm0 4h2v6h-2zm1-9C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm0 18c-4.41 0-8-3.59-8-8s3.59-8 8-8 8 3.59 8 8-3.59 8-8 8z"></path></svg></button></div></div><div class="sc-9d52d06f-1 bDNbpf"><div class="ipc-html-content ipc-html-content--base sc-9d52d06f-0 bVMrTF title-description-plot-container" role="presentation"><div class="ipc-html-content-inner-div" role="presentation">In a future where mutants are nearly extinct, an elderly and weary Logan leads a quiet life. But when Laura, a mutant child pursued by scientists, comes to him for help, he must get her to safety.</div></div></div></div></div></div>

In [45]:
first_movie.h3

In [84]:
a = first_movie.find('a')
a

In [56]:
first_name = first_movie.find('h3', class_='ipc-title__text').text
first_name

'1. Logan'

In [57]:
first_year = first_movie.h3.find('span', class_ = 'lister-item-year text-muted unbold')
first_year

In [62]:
first_year = first_movie.find('span', class_='dli-title-metadata-item').text
first_year

'2017'

In [81]:
rating_tag = first_movie.find('span', class_='ipc-rating-star') #span instead of strong

rating_text = rating_tag.text

first_imdb = float(rating_text.split()[0])

print("IMDb Rating:", first_imdb)

IMDb Rating: 8.1

In [85]:
first_mscore = first_movie.find('span', class_ = 'sc-9fe7b0ef-0 hDuMnh metacritic-score-box')
first_mscore = int(first_mscore.text)
print(first_mscore)

77

In [88]:
rating_text = first_movie.find('span', class_='ipc-rating-star').text

votes_text = rating_text.split()[1]

first_votes = votes_text.strip('()')

print("Votes:", first_votes)

Votes: 919K

In [92]:
names = []
years = []
imdb_ratings = []
metascores = []
votes = []

print("Starting the scraper...")

# 2. Loop through every single movie in our containers list
for container in movie_containers:
    
    # --- TITLE ---
    name = container.find('h3', class_='ipc-title__text').text
    names.append(name)
    
    # --- YEAR ---
    year = container.find('span', class_='dli-title-metadata-item').text
    years.append(year)
    
    # --- RATING & VOTES ---
    rating_tag = container.find('span', class_='ipc-rating-star')
    
    if rating_tag is not None:
        rating_text = rating_tag.text
        imdb = float(rating_text.split()[0])
        vote_count = rating_text.split()[1].strip('()')
    else:
        imdb = None
        vote_count = None
        
    imdb_ratings.append(imdb)
    votes.append(vote_count)
    
    mscore_tag = container.find('span', class_='metacritic-score-box')
    
    if mscore_tag is not None:
        mscore = int(mscore_tag.text.strip())
    else:
        mscore = None
        
    metascores.append(mscore)

print(f"Successfully scraped {len(names)} movies!")

Starting the scraper...
Successfully scraped 50 movies!

In [93]:
import pandas as pd
test_df = pd.DataFrame({'movie': names,
'year': years,
'imdb': imdb_ratings,
'metascore': metascores,
'votes': votes
})
print(test_df.info())
test_df

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   movie      50 non-null     str
 1   year       50 non-null     str
 2   imdb       50 non-null     float64
 3   metascore  41 non-null     float64
 4   votes      50 non-null     str
dtypes: float64(2), str(3)
memory usage: 2.1 KB
None

,movie,year,imdb,metascore,votes
0,1. Logan,2017,8.1,77.0,919K
1,2. Thor: Ragnarok,2017,7.9,74.0,887K
2,3. Guardians of the Galaxy Vol. 2,2017,7.6,67.0,822K
3,4. Get Out,2017,7.8,85.0,807K
4,5. Dunkirk,2017,7.8,94.0,801K
5,6. Spider-Man: Homecoming,2017,7.4,73.0,789K
6,7. Blade Runner 2049,2017,8.0,81.0,746K
7,8. Wonder Woman,2017,7.3,76.0,733K
8,9. Star Wars: Episode VIII - The Last Jedi,2017,6.8,84.0,714K
9,10. Coco,2017,8.4,81.0,697K
10,11. It,2017,7.3,69.0,689K
11,12. Baby Driver,2017,7.5,86.0,678K
12,"13. Three Billboards Outside Ebbing, Missouri",2017,8.1,88.0,602K
13,14. Money Heist,2017–2021,8.2,NaN,599K
14,15. John Wick: Chapter 2,2017,7.4,75.0,565K
15,16. Dark,2017–2020,8.7,NaN,535K
16,17. Justice League,2017,6.0,45.0,503K
17,18. Jumanji: Welcome to the Jungle,2017,6.9,58.0,498K
18,19. The Shape of Water,2017,7.3,87.0,473K
19,20. Kingsman: The Golden Circle,2017,6.7,44.0,399K
20,21. Mindhunter,2017–2019,8.6,NaN,392K
21,22. Ozark,2017–2022,8.4,NaN,388K
22,23. Pirates of the Caribbean: Dead Men Tell No...,2017,6.5,39.0,382K
23,24. Kong: Skull Island,2017,6.7,62.0,372K
24,25. Lady Bird,2017,7.4,93.0,361K
25,26. Beauty and the Beast,2017,7.1,65.0,357K
26,27. Call Me by Your Name,2017,7.8,94.0,355K
27,28. The Greatest Showman,2017,7.5,48.0,344K
28,29. Alien: Covenant,2017,6.4,65.0,343K
29,30. 13 Reasons Why,2017–2020,7.4,NaN,338K
30,31. War for the Planet of the Apes,2017,7.4,82.0,325K
31,32. Murder on the Orient Express,2017,6.5,52.0,320K
32,33. Wind River,2017,7.7,73.0,312K
33,34. The Punisher,2017–2019,8.4,NaN,298K
34,35. The Handmaid's Tale,2017–2025,8.3,NaN,294K
35,36. Life,2017,6.6,54.0,275K
36,37. The Fate of the Furious,2017,6.6,56.0,272K
37,38. Mother!,2017,6.6,76.0,267K
38,39. The Hitman's Bodyguard,2017,6.9,47.0,261K
39,"40. I, Tonya",2017,7.5,77.0,260K
40,41. King Arthur: Legend of the Sword,2017,6.7,41.0,246K
41,42. The End of the F***ing World,2017–2019,8.0,NaN,244K
42,43. Big Little Lies,2017–2026,8.4,NaN,243K
43,44. Darkest Hour,2017,7.4,75.0,242K
44,45. Ghost in the Shell,2017,6.3,52.0,239K
45,46. American Made,2017,7.1,65.0,231K
46,47. The Mummy,2017,5.4,34.0,221K
47,48. Atomic Blonde,2017,6.7,63.0,219K
48,49. Baywatch,2017,5.5,37.0,217K
49,50. The Killing of a Sacred Deer,2017,7.0,73.0,213K

In [128]:
from time import time, sleep
from random import randint
from IPython.display import clear_output
from requests import get
from bs4 import BeautifulSoup
import warnings

pages = ['1', '2', '3', '4', '5']
years_url = ['2017', '2018', '2019', '2020']

# Redeclaring the lists to store data in
names = []
years = []
imdb_ratings = []
metascores = []
votes = []

# Preparing the monitoring of the loop
start_time = time()
requests = 0
headers = {"Accept-Language": "en-US, en;q=0.5", "User-Agent": "Mozilla/5.0"}

print("Starting the massive scraper...")

# For every year in the interval 2017-2020
for year_url in years_url:
    
    # For every page in the interval 1-5 
    for page in pages:
        
        # Make a get request
        response = get('https://www.imdb.com/search/title/?release_date=' + year_url + '&sort=num_votes,desc&page=' + page, headers=headers)
        
        # Pause the loop so we don't spam IMDb's servers and get banned
        sleep(randint(8,15))
        
        # Monitor the requests
        requests += 1
        elapsed_time = time() - start_time
        print('Request: {}; Frequency: {} requests/s'.format(requests, requests/elapsed_time))
        clear_output(wait = True)
        
        # Throw a warning for non-200 status codes
        if response.status_code != 200:
            warnings.warn('Request: {}; Status code: {}'.format(requests, response.status_code))
            
        # Break the loop if the number of requests is greater than expected
        if requests > 72:
            warnings.warn('Number of requests was greater than expected.')
            break
            
        # Parse the content
        page_html = BeautifulSoup(response.text, 'html.parser')
        
        # Select all movie containers using the UPDATED IMDb tags!
        mv_containers = page_html.find_all('li', class_='ipc-metadata-list-summary-item')
        
        # Loop through our updated containers
        for container in mv_containers:
            
            # --- TITLE ---
            try:
                name = container.find('h3', class_='ipc-title__text').text
                names.append(name)
            except AttributeError:
                names.append(None)
            
            # --- YEAR ---
            try:
                year = container.find('span', class_='dli-title-metadata-item').text
                years.append(year)
            except AttributeError:
                years.append(None)
            
            # --- RATING & VOTES ---
            rating_tag = container.find('span', class_='ipc-rating-star')
            if rating_tag is not None:
                rating_text = rating_tag.text
                imdb = float(rating_text.split()[0])
                # Check if votes exist in the string before grabbing them
                if len(rating_text.split()) > 1:
                    vote_count = rating_text.split()[1].strip('()')
                else:
                    vote_count = None
            else:
                imdb = None
                vote_count = None
                
            imdb_ratings.append(imdb)
            votes.append(vote_count)
            
            # --- METASCORE ---
            mscore_tag = container.find('span', class_='metacritic-score-box')
            if mscore_tag is not None:
                mscore = int(mscore_tag.text.strip())
            else:
                mscore = None
                
            metascores.append(mscore)

print(f"Finished! Successfully scraped {len(names)} movies across multiple years and pages.")

Finished! Successfully scraped 0 movies across multiple years and pages.

C:\Users\tipqc\AppData\Local\Temp\ipykernel_31364\642595859.py:47: UserWarning: Request: 20; Status code: 202
  warnings.warn('Request: {}; Status code: {}'.format(requests, response.status_code))

In [95]:
movie_ratings = pd.DataFrame({'movie': names,
'year': years,
'imdb': imdb_ratings,
'metascore': metascores,
'votes': votes
})
print(movie_ratings.info())
movie_ratings.head(10)

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   movie      50 non-null     str
 1   year       50 non-null     str
 2   imdb       50 non-null     float64
 3   metascore  41 non-null     float64
 4   votes      50 non-null     str
dtypes: float64(2), str(3)
memory usage: 2.1 KB
None

                                        movie  year  imdb  metascore votes
0                                    1. Logan  2017   8.1       77.0  919K
1                           2. Thor: Ragnarok  2017   7.9       74.0  887K
2           3. Guardians of the Galaxy Vol. 2  2017   7.6       67.0  822K
3                                  4. Get Out  2017   7.8       85.0  807K
4                                  5. Dunkirk  2017   7.8       94.0  801K
5                   6. Spider-Man: Homecoming  2017   7.4       73.0  789K
6                        7. Blade Runner 2049  2017   8.0       81.0  746K
7                             8. Wonder Woman  2017   7.3       76.0  733K
8  9. Star Wars: Episode VIII - The Last Jedi  2017   6.8       84.0  714K
9                                    10. Coco  2017   8.4       81.0  697K

In [96]:
movie_ratings.tail(10)

                                   movie       year  imdb  metascore votes
40  41. King Arthur: Legend of the Sword       2017   6.7       41.0  246K
41      42. The End of the F***ing World  2017–2019   8.0        NaN  244K
42                   43. Big Little Lies  2017–2026   8.4        NaN  243K
43                      44. Darkest Hour       2017   7.4       75.0  242K
44                45. Ghost in the Shell       2017   6.3       52.0  239K
45                     46. American Made       2017   7.1       65.0  231K
46                         47. The Mummy       2017   5.4       34.0  221K
47                     48. Atomic Blonde       2017   6.7       63.0  219K
48                          49. Baywatch       2017   5.5       37.0  217K
49      50. The Killing of a Sacred Deer       2017   7.0       73.0  213K

In [98]:
movie_ratings.to_csv('movie_ratings.csv')

# Data Cleaning and Exploration

After gathering the data, we need to ensure the columns are in the correct data types for our analysis. We will clean the `year` column and verify our dataset.

In [106]:
movie_ratings['year'].unique()

<StringArray>
[     '2017', '2017–2021', '2017–2020', '2017–2019', '2017–2022', '2017–2025',
 '2017–2026']
Length: 7, dtype: str

In [102]:
movie_ratings.dtypes

movie            str
year             str
imdb         float64
metascore    float64
votes            str
dtype: object

In [107]:
movie_ratings['year'] = (movie_ratings.year.apply(lambda x:x.replace('(I)','')))

In [104]:
# View the first 10 rows of the final dataframe
movie_ratings['year'].unique()

<StringArray>
[     '2017', '2017–2021', '2017–2020', '2017–2019', '2017–2022', '2017–2025',
 '2017–2026']
Length: 7, dtype: str

In [108]:
movie_ratings['year'] = (movie_ratings.year.apply(lambda x:x.replace('(II)','')))

In [109]:
movie_ratings['year'] = (movie_ratings.year.apply(lambda x:x.replace('(III)','')))

In [110]:
movie_ratings['year'].unique()

<StringArray>
[     '2017', '2017–2021', '2017–2020', '2017–2019', '2017–2022', '2017–2025',
 '2017–2026']
Length: 7, dtype: str

In [111]:
movie_ratings['year'] = (movie_ratings.year.apply(lambda x:x.replace('(','')))

In [112]:
movie_ratings['year'].unique()

<StringArray>
[     '2017', '2017–2021', '2017–2020', '2017–2019', '2017–2022', '2017–2025',
 '2017–2026']
Length: 7, dtype: str

In [113]:
movie_ratings['year'] = (movie_ratings.year.apply(lambda x:x.replace(')','')))

In [114]:
movie_ratings['year'].unique()

<StringArray>
[     '2017', '2017–2021', '2017–2020', '2017–2019', '2017–2022', '2017–2025',
 '2017–2026']
Length: 7, dtype: str

In [126]:
# 1. Use a regular expression to extract ONLY the first 4 consecutive numbers (the starting year)
movie_ratings['year'] = movie_ratings['year'].astype(str).str.extract(r'(\d{4})')

# 2. Now that everything is a clean 4-digit number, convert the column to integers!
movie_ratings['year'] = movie_ratings['year'].astype(int)

# Check our work
movie_ratings['year'].unique()

array([2017])

In [127]:
movie_ratings['year'].unique()

array([2017])

In [118]:
movie_ratings.dtypes

movie            str
year           int64
imdb         float64
metascore    float64
votes            str
dtype: object

In [119]:
movie_ratings.head(10)

                                        movie  year  imdb  metascore votes
0                                    1. Logan  2017   8.1       77.0  919K
1                           2. Thor: Ragnarok  2017   7.9       74.0  887K
2           3. Guardians of the Galaxy Vol. 2  2017   7.6       67.0  822K
3                                  4. Get Out  2017   7.8       85.0  807K
4                                  5. Dunkirk  2017   7.8       94.0  801K
5                   6. Spider-Man: Homecoming  2017   7.4       73.0  789K
6                        7. Blade Runner 2049  2017   8.0       81.0  746K
7                             8. Wonder Woman  2017   7.3       76.0  733K
8  9. Star Wars: Episode VIII - The Last Jedi  2017   6.8       84.0  714K
9                                    10. Coco  2017   8.4       81.0  697K

In [120]:
movie_ratings.tail(10)

                                   movie  year  imdb  metascore votes
40  41. King Arthur: Legend of the Sword  2017   6.7       41.0  246K
41      42. The End of the F***ing World  2017   8.0        NaN  244K
42                   43. Big Little Lies  2017   8.4        NaN  243K
43                      44. Darkest Hour  2017   7.4       75.0  242K
44                45. Ghost in the Shell  2017   6.3       52.0  239K
45                     46. American Made  2017   7.1       65.0  231K
46                         47. The Mummy  2017   5.4       34.0  221K
47                     48. Atomic Blonde  2017   6.7       63.0  219K
48                          49. Baywatch  2017   5.5       37.0  217K
49      50. The Killing of a Sacred Deer  2017   7.0       73.0  213K

In [121]:
movie_ratings

,movie,year,imdb,metascore,votes
0,1. Logan,2017,8.1,77.0,919K
1,2. Thor: Ragnarok,2017,7.9,74.0,887K
2,3. Guardians of the Galaxy Vol. 2,2017,7.6,67.0,822K
3,4. Get Out,2017,7.8,85.0,807K
4,5. Dunkirk,2017,7.8,94.0,801K
5,6. Spider-Man: Homecoming,2017,7.4,73.0,789K
6,7. Blade Runner 2049,2017,8.0,81.0,746K
7,8. Wonder Woman,2017,7.3,76.0,733K
8,9. Star Wars: Episode VIII - The Last Jedi,2017,6.8,84.0,714K
9,10. Coco,2017,8.4,81.0,697K
10,11. It,2017,7.3,69.0,689K
11,12. Baby Driver,2017,7.5,86.0,678K
12,"13. Three Billboards Outside Ebbing, Missouri",2017,8.1,88.0,602K
13,14. Money Heist,2017,8.2,NaN,599K
14,15. John Wick: Chapter 2,2017,7.4,75.0,565K
15,16. Dark,2017,8.7,NaN,535K
16,17. Justice League,2017,6.0,45.0,503K
17,18. Jumanji: Welcome to the Jungle,2017,6.9,58.0,498K
18,19. The Shape of Water,2017,7.3,87.0,473K
19,20. Kingsman: The Golden Circle,2017,6.7,44.0,399K
20,21. Mindhunter,2017,8.6,NaN,392K
21,22. Ozark,2017,8.4,NaN,388K
22,23. Pirates of the Caribbean: Dead Men Tell No...,2017,6.5,39.0,382K
23,24. Kong: Skull Island,2017,6.7,62.0,372K
24,25. Lady Bird,2017,7.4,93.0,361K
25,26. Beauty and the Beast,2017,7.1,65.0,357K
26,27. Call Me by Your Name,2017,7.8,94.0,355K
27,28. The Greatest Showman,2017,7.5,48.0,344K
28,29. Alien: Covenant,2017,6.4,65.0,343K
29,30. 13 Reasons Why,2017,7.4,NaN,338K
30,31. War for the Planet of the Apes,2017,7.4,82.0,325K
31,32. Murder on the Orient Express,2017,6.5,52.0,320K
32,33. Wind River,2017,7.7,73.0,312K
33,34. The Punisher,2017,8.4,NaN,298K
34,35. The Handmaid's Tale,2017,8.3,NaN,294K
35,36. Life,2017,6.6,54.0,275K
36,37. The Fate of the Furious,2017,6.6,56.0,272K
37,38. Mother!,2017,6.6,76.0,267K
38,39. The Hitman's Bodyguard,2017,6.9,47.0,261K
39,"40. I, Tonya",2017,7.5,77.0,260K
40,41. King Arthur: Legend of the Sword,2017,6.7,41.0,246K
41,42. The End of the F***ing World,2017,8.0,NaN,244K
42,43. Big Little Lies,2017,8.4,NaN,243K
43,44. Darkest Hour,2017,7.4,75.0,242K
44,45. Ghost in the Shell,2017,6.3,52.0,239K
45,46. American Made,2017,7.1,65.0,231K
46,47. The Mummy,2017,5.4,34.0,221K
47,48. Atomic Blonde,2017,6.7,63.0,219K
48,49. Baywatch,2017,5.5,37.0,217K
49,50. The Killing of a Sacred Deer,2017,7.0,73.0,213K

Individual Webscraping - Anime List

In [145]:
pip install selenium webdriver-manager

Requirement already satisfied: selenium in c:\users\tipqc\appdata\local\programs\python\python312\lib\site-packages (4.41.0)
Requirement already satisfied: webdriver-manager in c:\users\tipqc\appdata\local\programs\python\python312\lib\site-packages (4.0.2)
Requirement already satisfied: certifi>=2026.1.4 in c:\users\tipqc\appdata\local\programs\python\python312\lib\site-packages (from selenium) (2026.1.4)
Requirement already satisfied: trio<1.0,>=0.31.0 in c:\users\tipqc\appdata\local\programs\python\python312\lib\site-packages (from selenium) (0.33.0)
Requirement already satisfied: trio-websocket<1.0,>=0.12.2 in c:\users\tipqc\appdata\local\programs\python\python312\lib\site-packages (from selenium) (0.12.2)
Requirement already satisfied: typing_extensions<5.0,>=4.15.0 in c:\users\tipqc\appdata\local\programs\python\python312\lib\site-packages (from selenium) (4.15.0)
Requirement already satisfied: urllib3<3.0,>=2.6.3 in c:\users\tipqc\appdata\local\programs\python\python312\lib\site-packages (from urllib3[socks]<3.0,>=2.6.3->selenium) (2.6.3)
Requirement already satisfied: websocket-client<2.0,>=1.8.0 in c:\users\tipqc\appdata\local\programs\python\python312\lib\site-packages (from selenium) (1.9.0)
Requirement already satisfied: requests in c:\users\tipqc\appdata\local\programs\python\python312\lib\site-packages (from webdriver-manager) (2.32.5)
Requirement already satisfied: python-dotenv in c:\users\tipqc\appdata\local\programs\python\python312\lib\site-packages (from webdriver-manager) (1.2.1)
Requirement already satisfied: packaging in c:\users\tipqc\appdata\roaming\python\python312\site-packages (from webdriver-manager) (25.0)
Requirement already satisfied: attrs>=23.2.0 in c:\users\tipqc\appdata\local\programs\python\python312\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (25.4.0)
Requirement already satisfied: sortedcontainers in c:\users\tipqc\appdata\local\programs\python\python312\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (2.4.0)
Requirement already satisfied: idna in c:\users\tipqc\appdata\local\programs\python\python312\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (3.11)
Requirement already satisfied: outcome in c:\users\tipqc\appdata\local\programs\python\python312\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in c:\users\tipqc\appdata\local\programs\python\python312\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (1.3.1)
Requirement already satisfied: cffi>=1.14 in c:\users\tipqc\appdata\local\programs\python\python312\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (2.0.0)
Requirement already satisfied: wsproto>=0.14 in c:\users\tipqc\appdata\local\programs\python\python312\lib\site-packages (from trio-websocket<1.0,>=0.12.2->selenium) (1.3.2)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in c:\users\tipqc\appdata\local\programs\python\python312\lib\site-packages (from urllib3[socks]<3.0,>=2.6.3->selenium) (1.7.1)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\tipqc\appdata\local\programs\python\python312\lib\site-packages (from requests->webdriver-manager) (3.4.4)
Requirement already satisfied: pycparser in c:\users\tipqc\appdata\local\programs\python\python312\lib\site-packages (from cffi>=1.14->trio<1.0,>=0.31.0->selenium) (3.0)
Requirement already satisfied: h11<1,>=0.16.0 in c:\users\tipqc\appdata\local\programs\python\python312\lib\site-packages (from wsproto>=0.14->trio-websocket<1.0,>=0.12.2->selenium) (0.16.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [9]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = 'https://myanimelist.net/topanime.php?type=airing'
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/120.0.0.0 Safari/537.36'}

print("Step 1: Fetching page...")
response = requests.get(url, headers=headers)
soup = BeautifulSoup(response.text, 'html.parser')

# Find the rows - MAL consistently uses 'ranking-list'
rows = soup.find_all('tr', class_='ranking-list')
print(f"Step 2: Found {len(rows)} rows.")

data = []

for row in rows:
    # --- BETTER TITLE SELECTION ---
    # We look for the <h3> tag inside the row, regardless of its class name
    title_tag = row.find('h3') 
    title = title_tag.text.strip() if title_tag else "N/A"
    
    # --- BETTER INFO SELECTION ---
    # We look for the div containing the word 'information'
    info_tag = row.find('div', class_='information')
    info_text = info_tag.text.strip().replace('\n', ' ') if info_tag else "N/A"
    
    # --- SCORE SELECTION ---
    score_tag = row.find('span', class_='text')
    score = score_tag.text.strip() if score_tag else "N/A"

    # Only add to data if we actually found a title
    if title != "N/A":
        data.append({
            'Title': title,
            'Details': info_text,
            'Score': score
        })

# Create DataFrame
df = pd.DataFrame(data)

# --- THE FIX FOR THE EMPTY FILE ---
if not df.empty:
    # 1. Print the count to confirm Python has the data in its brain
    print(f"Step 3: {len(df)} items found. Writing to file...")
    
    # 2. Force the save
    df.to_csv('top_airing_anime.csv', index=False, encoding='utf-8-sig')
    
    # 3. Final verification
    print("Step 4: File 'top_airing_anime.csv' updated successfully.")
    display(df.head(50))
else:
    print("Step 3: DATA LIST IS EMPTY. The tags might be wrong or the page didn't load.")

Step 1: Fetching page...
Step 2: Found 50 rows.
Step 3: 50 items found. Writing to file...
Step 4: File 'top_airing_anime.csv' updated successfully.

,Title,Details,Score
0,Sousou no Frieren 2nd Season,"TV (10 eps) Jan 2026 - 404,28...",9.18
1,One Piece,"TV (? eps) Oct 1999 - 2,640,8...",8.73
2,Ikoku Nikki,"TV (13 eps) Jan 2026 - 68,600...",8.68
3,Jujutsu Kaisen: Shimetsu Kaiyuu - Zenpen,"TV (12 eps) Jan 2026 - 365,49...",8.58
4,[Oshi no Ko] 3rd Season,TV (11 eps) Jan 2026 - Mar 2026 ...,8.55
5,Chiikawa,"TV (? eps) Apr 2022 - 17,957 ...",8.54
6,Fate/strange Fake,"TV (13 eps) Jan 2026 - 133,26...",8.50
7,Xian Ni,"ONA (? eps) Sep 2023 - 10,403...",8.46
8,Tian Guan Cifu Short Film,"ONA (? eps) Feb 2025 - 10,584...",8.45
9,Doupo Cangqiong: Nian Fan,"ONA (209 eps) Jul 2022 - 11,9...",8.42
10,Medalist 2nd Season,"TV (9 eps) Jan 2026 - 30,715 ...",8.41
11,Tunshi Xingkong 4th Season,"ONA (175 eps) Oct 2023 - 5,72...",8.37
12,Golden Kamuy: Saishuushou,"TV (13 eps) Jan 2026 - 49,490...",8.33
13,Mushen Ji,"ONA (? eps) Oct 2024 - 15,184...",8.28
14,Shen Yin Wangzuo 2nd Season,"ONA (? eps) Nov 2022 - 7,534 ...",8.23
15,Jigokuraku 2nd Season,"TV (12 eps) Jan 2026 - 302,69...",8.22
16,Yuusha-kei ni Shosu: Choubatsu Yuusha 9004-tai...,"TV (12 eps) Jan 2026 - 223,54...",8.21
17,Seihantai na Kimi to Boku,"TV (12 eps) Jan 2026 - 112,24...",8.19
18,Meitantei Conan,"TV (? eps) Jan 1996 - 375,540...",8.18
19,Holo no Graffiti,"ONA (? eps) May 2019 - 58,523...",8.15
20,Douluo Dalu II: Jueshi Tangmen,"ONA (156 eps) Jun 2023 - 6,79...",8.06
21,Enen no Shouboutai: San no Shou Part 2,"TV (13 eps) Jan 2026 - 147,89...",8.03
22,MF Ghost 3rd Season,"TV (? eps) Jan 2026 - 26,020 ...",7.93
23,Tamon-kun Ima Docchi!?,"TV (13 eps) Jan 2026 - 64,484...",7.88
24,Wanmei Shijie,"ONA (286 eps) Apr 2021 - 13,9...",7.86
25,Crayon Shin-chan,"TV (? eps) Apr 1992 - 93,487 ...",7.81
26,Doraemon (2005),"TV (? eps) Apr 2005 - 23,072 ...",7.75
27,Zhe Tian,"ONA (156 eps) May 2023 - 3,75...",7.72
28,Guangyin Zhi Wai,ONA (26 eps) Dec 2025 - 845 m...,7.69
29,"Himesama ""Goumon"" no Jikan desu 2nd Season","TV (12 eps) Jan 2026 - 22,232...",7.66
30,Shibou Yuugi de Meshi wo Kuu.,TV (11 eps) Jan 2026 - Mar 2026 ...,7.65
31,Fumetsu no Anata e Season 3,"TV (22 eps) Oct 2025 - 141,67...",7.64
32,Gensou Mangekyou: The Memories of Phantasm,"OVA (? eps) Aug 2011 - 10,757...",7.59
33,Toujima Tanzaburou wa Kamen Rider ni Naritai,TV (24 eps) Oct 2025 - Mar 2026 ...,7.57
34,Wushen Zhuzai,"ONA (720 eps) Mar 2020 - 6,74...",7.57
35,Gnosia,TV (21 eps) Oct 2025 - Mar 2026 ...,7.56
36,Meitantei Precure!,"TV (? eps) Feb 2026 - 3,544 m...",7.54
37,Koupen-chan,"TV (? eps) Apr 2025 - 6,285 m...",7.51
38,"Yamato yo, Towa ni: Rebel 3199","Movie (? eps) Jul 2024 - 5,24...",7.51
39,Uruwashi no Yoi no Tsuki,"TV (? eps) Jan 2026 - 59,844 ...",7.49
40,Mato Seihei no Slave 2,"TV (12 eps) Jan 2026 - 79,689...",7.47
41,Chibi Maruko-chan (1995),"TV (? eps) Jan 1995 - 8,628 m...",7.42
42,Lian Qi Shi Wan Nian,"ONA (360 eps) Feb 2023 - 3,74...",7.42
43,Pokemon (2023),"TV (? eps) Apr 2023 - 41,043 ...",7.41
44,Sousou no Frieren: ●● no Mahou,"ONA (? eps) Oct 2023 - 23,477...",7.39
45,Toumei Otoko to Ningen Onna: Sonouchi Fuufu ni...,"TV (12 eps) Jan 2026 - 36,897...",7.38
46,Vigilante: Boku no Hero Academia Illegals 2nd ...,"TV (13 eps) Jan 2026 - 74,202...",7.37
47,Xianwu Zhuan 2nd Season,"ONA (147 eps) Sep 2023 - 2,29...",7.37
48,Hifuu Katsudou Kiroku: The Sealed Esoteric His...,"OVA (? eps) Dec 2015 - 9,579 ...",7.36
49,Jian Lai 2nd Season,ONA (27 eps) Dec 2025 - 810 m...,7.30

**Conclusion**

In this activity I have learned and strengthened how to perform webscraping in python using BeautifulSoup and Selenium as well as the challenges I have faced in them. In the first section, I have encountered some limitations regarding the webcam and audio codes as there is no webcam in the school PC I am working with although the code was working as I converted the google colab code into vscode's and second, the school system does not permit the program to use the audio. Moving to the next step which was the cat webscraping program, I noticed that the school has also blocked the chrome as being a user agent and so I used firefox to effectively use it as the agent for the rest of my activities. The cat pictures successfully loaded into the files as I have loaded them using the program by being accessed by the user agent, parsed as the program opens each cat picture in the google image source link then saved to the file. During the entire IMDB section, I have performed debugging on the key issues regarding the updated site's classes, I manually fetched the correct classes of the top ratings page and then used an agent to load at least 50 of the titles by scrolling to the end. Lastly, I kept updating eventually storing the data into an array for the pandas dataframe to be processed and loaded into the csv file. I did the same logic in the site MyAnimeList to webscrape the top 50 anime using their titles, details and scores loaded into the csv file.